{
  "hash": "493fe18e0219e5cec193a86c53750744",
  "result": {
    "engine": "julia",
    "markdown": "---\nsubtitle: Nonlinear Optimization\nengine: julia\n---\n\n# 非線形最適化 {#sec-nonlinear-opt}\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\nusing Roots\nusing NonlinearSolve\nusing Optim\nusing Optimization\nimport OptimizationNLopt\nimport NLopt\nusing JuMP\nusing Ipopt\nusing Plots\nusing LaTeXStrings\n```\n:::\n\n\n\n\n\n\n経済モデルを数値的に解く作業は, 多くの場合「非線形方程式 $f(\\mathbf{x}) = \\mathbf{0}$ を解く」か「非線形関数を最大化・最小化する」のどちらかに帰着します. 両者は表裏一体です. 最大化問題は一階条件を導出すれば方程式として解けますし, 最適化アルゴリズムの多くは方程式の解法の analogy として理解できます. 本章では, 前半で非線形方程式の解法である**求根法** (root finding) を, 後半で目的関数を直接扱う**非線形最適化** (nonlinear optimization) を解説します.\n\n## 求根法 {#sec-root-finding}\n\nモデルを解く際に, $f(\\mathbf{x}) = \\mathbf{0}$ となるような $\\mathbf{x}$ を求める必要があることが多いです. 例えば, 家計の最大化問題を解く際の一階条件は, 一般に非線形方程式の形をとります. ごく特殊なケースを除いて, 解析的に解くことができないため, 数値的に解を求める必要があります. この様な非線形方程式の数値解法は, 一変数の場合と多変数の場合に分けられます. 以下では, それぞれの方法について解説します.\n\n### 一変数の非線形方程式\n\nここでは例として, 次のようなCRRA効用関数を用いた家計の最大化問題を考えてみましょう.\n\n$$\n\\max_{c, l} \\frac{c^{1-\\gamma_c}}{1-\\gamma_c} + \\alpha_l \\frac{l^{1-\\gamma_l}}{1-\\gamma_l} \\quad \\text{s.t.} \\quad c = w (1-l)\n$${#eq-max-utility}\nこの問題は以下の一階条件の解を求めることで解くことができます.\n\n$$\nw^{1-\\gamma_c} (1-l)^{-\\gamma_c} - \\alpha_l l^{-\\gamma_l} = 0.\n$$\n\n::: {#fn-foc-crra .cell execution_count=1}\n``` {.julia .cell-code}\nfoc(l; w=1.0, γ_c=1.5, α_l=1.2, γ_l=1.5) =\n    w^(1 - γ_c) * (1 - l)^(-γ_c) - α_l * l^(-γ_l)\n```\n:::\n\n\n\nこれを図で表すと @fig-foc-crra のようになります. 求めたいのは, この関数と $y = 0$ の交点の値です.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code code-fold=\"true\"}\nplot(0.1:0.01:0.9, foc, label=false, lw=2)\nhline!([0.0], ls=:dash, lw=2, label=false, color=:black)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![FOC for CRRA utility. $f(l) = w^{1-\\gamma_c} (1-l)^{-\\gamma_c} - \\alpha_l l^{-\\gamma_l}$.](nlopt_files/figure-typst/fig-foc-crra-output-1.svg){#fig-foc-crra}\n:::\n:::\n\n\n\nこの様な一変数の非線形方程式 $f(x) = 0$ の解法として, 以下の2つの選択肢があります.\n\n1. **Non-bracketing method**: 初期値 $x_0$ からスタートして, $f(x_n)$ が十分0に近づくまで反復的に計算. (ニュートン法など)\n1. **Bracketing method**: 区間 $[a, b]$ を選び, 区間を狭めていくことで解を求める. (二分法など)\n\n一般に, Non-bracketing method は収束が速い代わりにその収束は保証されません. 一方で, Bracketing method は収束がわずかに遅い代わりに, 解が存在する区間を保証することができます. 以下では, その理由とそれぞれの適した利用場面を解説します.\n\n#### Non-bracketing method {#sec-non-bracketing}\n\nNon-bracketing method は基本的には一階微分を利用し, 初期値 $x_0$ からスタートして反復的に解を求めます. ここでは, 最も古典的で簡単なニュートン法を紹介します.\n\n::: {.callout-tip}\n\n## ニュートン法\n\n1. 初期値 $x_0$ を選ぶ. また停止条件として十分小さい $\\epsilon > 0$ を選ぶ.\n1. $x_{n+1} = x_n - \\frac{f(x_n)}{f'(x_n)}$ を計算する.\n1. $|f(x_{n+1})| < \\epsilon$ ならば停止し, $x_{n+1}$ を解として返す. そうでなければ, $n \\leftarrow n+1$ として2に戻る.\n\n:::\n\n![Visualization of Newton Method](/static/cetz/newton_method.svg){#fig-newton-method width=80%}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndfoc(l; w=1.0, γ_c=1.5, α_l=1.2, γ_l=1.5) =\n    w^(1 - γ_c) * γ_c * (1 - l)^(-γ_c - 1) + α_l * γ_l * l^(-γ_l - 1)\n\nfind_zero((foc, dfoc), 0.5, Roots.Newton())\n```\n\n::: {#find-zero-newton .cell-output .cell-output-display execution_count=1}\n```\n0.530349570343484\n```\n:::\n:::\n\n\n\n実際に `foc` の上でニュートン法が収束していく様子を見てみましょう. 初期値を $x_0 = 0.15$ とし, スライダー (Iteration $N$) を動かすと, 各反復での接線 (赤) が引かれ, その $x$ 切片が次の点 $x_{N+1}$ になります. 接線が急な最初の一歩で大きく動き, 数回の反復で根 (灰色の破線) に急速に近づく様子が確認できます.\n\n\n\n\n```{ojs}\n//| label: ojs-newton-load\n//| echo: false\nnewton_iters = FileAttachment(\"static/data/newton_iterations.csv\")\n  .csv({typed: true})\nnewton_curve = FileAttachment(\"static/data/newton_curve.csv\").csv({typed: true})\nn_newton = d3.max(newton_iters, d => d.iter)\nsub = (n) => n.toString().split(\"\").map(c => \"₀₁₂₃₄₅₆₇₈₉\"[+c]).join(\"\")\n```\n\n```{ojs}\n//| label: ojs-newton-slider\n//| echo: false\nviewof nstep = {\n  const input = Inputs.range([0, n_newton],\n    {step: 1, value: 0, label: \"Iteration N\", width: 420});\n  input.style.fontSize = \"17px\";\n  return input;\n}\n```\n\n```{ojs}\n//| label: ojs-newton-fig\n//| echo: false\n{\n  const cur = newton_iters.find(d => d.iter === nstep);\n  const root = newton_iters[newton_iters.length - 1].xnext;\n  const [xL, xR] = [0.12, 0.60];\n  const ydom = [d3.min(newton_iters, d => d.f) * 1.06, 2.5];\n  // tangent line y = f(x_N) + f'(x_N)(x - x_N), across the whole range\n  const tangent = [{x: xL, y: cur.f + cur.d * (xL - cur.x)},\n                   {x: xR, y: cur.f + cur.d * (xR - cur.x)}];\n  return Plot.plot({\n    width: 620,\n    height: 420,\n    marginLeft: 55,\n    marginBottom: 48,\n    style: {fontSize: \"16px\"},\n    x: {label: \"Leisure l\", domain: [xL, xR]},\n    y: {label: \"f(l)\", domain: ydom},\n    marks: [\n      Plot.ruleY([0], {stroke: \"#999999\", strokeDasharray: \"3 3\"}),\n      Plot.ruleX([root], {stroke: \"#cccccc\", strokeDasharray: \"4 3\"}),\n      Plot.line(newton_curve,\n        {x: \"x\", y: \"f\", stroke: \"#5c363a\", strokeWidth: 2}),\n      Plot.line(tangent, {x: \"x\", y: \"y\", stroke: \"#c2676d\", strokeWidth: 2.5}),\n      // dotted drop from x_N on the axis up to the point (x_N, f(x_N))\n      Plot.line([{x: cur.x, y: 0}, {x: cur.x, y: cur.f}],\n        {x: \"x\", y: \"y\", stroke: \"#0f6a81\",\n         strokeDasharray: \"3 3\", strokeWidth: 1.5}),\n      Plot.dot([cur], {x: \"x\", y: \"f\", r: 5, fill: \"#0f6a81\"}),\n      Plot.dot([cur], {x: \"x\", y: 0, r: 5, fill: \"#0f6a81\"}),\n      Plot.dot([cur], {x: \"xnext\", y: 0, r: 5, fill: \"#c2676d\"}),\n      Plot.text([cur], {x: \"x\", y: 0, text: () => `x${sub(nstep)}`,\n        fill: \"#0f6a81\", dx: -14, dy: 16, fontSize: 16}),\n      Plot.text([cur], {x: \"xnext\", y: 0, text: () => `x${sub(nstep + 1)}`,\n        fill: \"#c2676d\", dx: 8, dy: 16, fontSize: 16}),\n      Plot.text([`N = ${nstep}`],\n        {frameAnchor: \"top-left\", dx: 10, dy: 10,\n         fontSize: 20, fontWeight: 600})\n    ]\n  })\n}\n```\n\nニュートン法は解の近くでは反復ごとに有効数字が倍増する2次収束を示し, わずか数回で高精度の解に達します. 一方で, 導関数 $f'$ がゼロに近い点や初期値が悪い場合には反復が定義域の外に飛び出して発散することもあり, 収束は保証されません.\n\n**Hybrid method**\n\nJuliaの`Roots.jl`のデフォルトのNon-bracketing method (`Order0()`)は, 厳密にはBracketing methodも一部利用します. また一階微分も必要としないため, より汎用的に利用することができます. ただし, 収束が速く収束が保証されない性質はNon-bracketing methodと同じです.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nl = find_zero(foc, 0.5)\n```\n\n::: {#find-zero-hybrid .cell-output .cell-output-display execution_count=1}\n```\n0.530349570343484\n```\n:::\n:::\n\n\n\n\n**定義域の変換**\n\nNon-bracketing method では, $x_{n+1}$ の値を更新する際に, 必ずしも $x_{n+1}$ が定義域内にあることが保証されません. 例えば, 今回の例では 余暇時間ですので, $l \\in (0, 1)$ ですが, 初期値や関数形によっては, $l < 0$ や $l > 1$ となる可能性があります.\n\nこの場合, 端点解が存在するかどうかを確認する必要があります. 端点解が想定される場合は, 次節で説明するように Bracketing method を利用することが適しています. 今回の例では, 端点解が存在しないため ($l = 0, 1$ のどちらにおいても効用が負の無限大に発散するため), Non-bracketing method での解の収束が保証されています. 以下の様な定義域の変換を用いることで, 解の収束を保証することができます.\n\n::: {.callout-note}\n\n## 定義域の変換\n\n$x$ が区間 $(a, b)$ で定義されるとき, 以下の変換を用いて定義域を $(-\\infty, \\infty)$ にすることができる.\n\n$$\nx = \\frac{a + b \\exp y}{1 + \\exp y}\n$$\n\n明らかに, $y \\rightarrow -\\infty$ のとき $x \\rightarrow a$, $y \\rightarrow \\infty$ のとき $x \\rightarrow b$ となる.\n\n:::\n\n今回の例では, $l = \\frac{1}{1 + \\exp(-y)}$ (つまり[シグモイド関数](https://ja.wikipedia.org/wiki/%E3%82%B7%E3%82%B0%E3%83%A2%E3%82%A4%E3%83%89%E9%96%A2%E6%95%B0)) という変換を用いることができます.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ny = find_zero(y -> foc(1 / (1 + exp(-y))), 0.0)\nl = 1 / (1 + exp(-y))\n```\n\n::: {#find-zero-transform .cell-output .cell-output-display execution_count=1}\n```\n0.530349570343484\n```\n:::\n:::\n\n\n\n#### Bracketing method\n\nBracketing method は, 解が存在する区間 $[a, b]$ を選び, その区間を狭めていくことで解を求めます. ここでは最も基本的な二分法を用いることで解を求めることができます.\n\n::: {.callout-tip}\n\n## 二分法\n\n1. 区間 $[a, b]$ を選ぶ. また停止条件として十分小さい $\\epsilon > 0$ を選ぶ.\n1. $f(a) \\cdot f(b) < 0$ ならば, $c = \\frac{a + b}{2}$ を計算する.\n1. $|f(c)| < \\epsilon$ ならば, $c$ を解として返す. そうでなければ, $f(a) \\cdot f(c) < 0$ ならば, $b \\leftarrow c$ として2に戻る. そうでなければ, $a \\leftarrow c$ として2に戻る.\n\n:::\n\n\n![Visualization of Bisection Method](/static/cetz/bisection_method.svg){#fig-bisection-method width=80%}\n\n例えば, 今回の例では $l \\in (0, 1)$ ですので, $l = 0$ と $l = 1$ で効用が発散することから, 解が存在する区間は $(0, 1)$ です. なお, 端点でFOCが定義されてない場合も多いので, 端点より微小に内側の区間を選ぶことが多いです.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nϵ = 1e-9\nl = find_zero(foc, (ϵ, 1 - ϵ))\n```\n\n::: {#find-zero-bracketing .cell-output .cell-output-display execution_count=1}\n```\n0.530349570343484\n```\n:::\n:::\n\n\n\n二分法が区間を狭めていく様子も見てみましょう. 開始区間を $[a_0, b_0] = [0.4, 0.8]$ とし, スライダー (Iteration $N$) を動かすと, 中点 $c_N$ での符号に応じて区間 (水色の帯) が半分ずつに狭まっていきます. ニュートン法と違い解は常に区間内に保証されますが, 区間幅は毎回半分になるだけなので, 同じ精度に達するにはより多くの反復が必要です.\n\n\n\n\n```{ojs}\n//| label: ojs-bisection-load\n//| echo: false\nbisect_iters = FileAttachment(\"static/data/bisection_iterations.csv\")\n  .csv({typed: true})\nbisect_curve = FileAttachment(\"static/data/bisection_curve.csv\")\n  .csv({typed: true})\nn_bisect = d3.max(bisect_iters, d => d.iter)\n```\n\n```{ojs}\n//| label: ojs-bisection-slider\n//| echo: false\nviewof mstep = {\n  const input = Inputs.range([0, n_bisect],\n    {step: 1, value: 0, label: \"Iteration N\", width: 420});\n  input.style.fontSize = \"17px\";\n  return input;\n}\n```\n\n```{ojs}\n//| label: ojs-bisection-fig\n//| echo: false\n{\n  const cur = bisect_iters.find(d => d.iter === mstep);\n  const root = bisect_iters[bisect_iters.length - 1].c;\n  const [xL, xR] = [0.37, 0.82];\n  const ydom = [-4, 6];\n  const band = [{x1: cur.a, x2: cur.b, y1: ydom[0], y2: ydom[1]}];\n  return Plot.plot({\n    width: 620,\n    height: 420,\n    marginLeft: 55,\n    marginBottom: 48,\n    style: {fontSize: \"16px\"},\n    x: {label: \"Leisure l\", domain: [xL, xR]},\n    y: {label: \"f(l)\", domain: ydom},\n    marks: [\n      Plot.rect(band, {x1: \"x1\", x2: \"x2\", y1: \"y1\", y2: \"y2\",\n        fill: \"#45939c\", fillOpacity: 0.12}),\n      Plot.ruleY([0], {stroke: \"#999999\", strokeDasharray: \"3 3\"}),\n      Plot.ruleX([root], {stroke: \"#cccccc\", strokeDasharray: \"4 3\"}),\n      Plot.line(bisect_curve,\n        {x: \"x\", y: \"f\", stroke: \"#5c363a\", strokeWidth: 2}),\n      Plot.ruleX([cur], {x: \"a\", stroke: \"#45939c\", strokeWidth: 1.5}),\n      Plot.ruleX([cur], {x: \"b\", stroke: \"#45939c\", strokeWidth: 1.5}),\n      // midpoint c_N: evaluated on the curve, with a dotted drop to the axis\n      Plot.line([{x: cur.c, y: 0}, {x: cur.c, y: cur.fc}],\n        {x: \"x\", y: \"y\", stroke: \"#c2676d\",\n         strokeDasharray: \"3 3\", strokeWidth: 1.5}),\n      Plot.dot([cur], {x: \"c\", y: \"fc\", r: 5, fill: \"#c2676d\"}),\n      Plot.dot([cur], {x: \"c\", y: 0, r: 5, fill: \"#c2676d\"}),\n      Plot.text([cur], {x: \"a\", y: 0, text: () => `a${sub(mstep)}`,\n        fill: \"#45939c\", dx: -12, dy: 16, fontSize: 16}),\n      Plot.text([cur], {x: \"b\", y: 0, text: () => `b${sub(mstep)}`,\n        fill: \"#45939c\", dx: 12, dy: 16, fontSize: 16}),\n      Plot.text([cur], {x: \"c\", y: 0, text: () => `c${sub(mstep)}`,\n        fill: \"#c2676d\", dx: 0, dy: cur.fc > 0 ? 18 : -16, fontSize: 16}),\n      Plot.text([`N = ${mstep}`],\n        {frameAnchor: \"top-left\", dx: 10, dy: 10,\n         fontSize: 20, fontWeight: 600})\n    ]\n  })\n}\n```\n\n二分法は各反復で区間幅がちょうど半分になる線形収束です. 収束は遅いものの, 初期区間の両端が異符号でありさえすれば必ず解に収束する頑健さが利点です.\n\n**端点解の存在**\n\n以下の様なカップルの意思決定問題を考えてみましょう.\n\n$$\n\\max_{c_m, c_f, l_m, l_f} u(c_m, l_m) + u(c_f, l_f)\n$${#eq-couple-problem}\n\nsubject to\n\n$$\nc_m + c_f = w_m (1 - l_m) + w_f (1 - l_f).\n$$\n\n一階条件から以下の関係が導けます:\n\n$$\n\\frac{l_m}{l_f} = \\left(\\frac{w_f}{w_m}\\right)^{\\frac{1}{\\gamma_l}}.\n$$\n\nこの関係から一方の相対賃金が十分に大きい場合, 例えば $w_m \\gg w_f$ の場合, $l_f > 1$ となる可能性があります ($l_m$ は余暇時間のため, 0よりある程度大きい値をとるということが想像できます.) 内点解が存在する場合の $l_f$ に関する一階条件は以下のようになります.\n\n$$\nw_m\\left(1-\\left(\\frac{w_f}{w_m}\\right)^{\\frac{1}{\\gamma_l}}l_f\\right) + w_f(1-l_f) - 2\\left(\\frac{w_f}{\\alpha_l}\\right)^{\\frac{1}{\\gamma_c}}l_f^{\\frac{\\gamma_l}{\\gamma_c}} = 0.\n$$\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code code-fold=\"true\"}\nfunction foc_bargaining(l_f; w_m=1.0, w_f=0.5, γ_c=1.5, α_l=1.2, γ_l=1.5)\n    return w_m * (1 - (w_f / w_m)^(1 / γ_l) * l_f) + w_f * (1 - l_f) -\n           2 * (w_f / α_l)^(1 / γ_c) * l_f^(γ_l / γ_c)\nend\n\nlf_grid = 0.01:0.01:0.99\ncols = [mypalette[6], mypalette[2], mypalette[4]]\np = plot(xlabel=L\"l_f\", legend=false, xlims=(0.0, 1.13))\nfor (i, wf) in enumerate([1.0, 0.5, 0.1])\n    ys = foc_bargaining.(lf_grid; w_f=wf)\n    plot!(p, lf_grid, ys, lw=2, color=cols[i])\n    # direct label at the right end of each line\n    annotate!(p, 1.0, ys[end], text(L\"w_f = %$wf\", 9, :black, :left))\nend\nhline!(p, [0.0], ls=:dash, lw=2, label=false, color=:black)\np\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![**FOC for bargaining problem.** $w_m = 1.0$, $\\alpha_l = 1.2$, $\\gamma_c = \\gamma_l = 1.5$.](nlopt_files/figure-typst/fig-foc-bargaining-output-1.svg){#fig-foc-bargaining}\n:::\n:::\n\n\n\n\nまた, $l_f = 1$ における一階条件は以下のようになります.\n\n$$\nw_m(1-l_m) - 2\\left(\\frac{w_m}{\\alpha_l}\\right)^{\\frac{1}{\\gamma_c}} l_m^{\\frac{\\gamma_l}{\\gamma_c}} = 0.\n$$\n\nこの様な場合, Bracketing method の考えが有効です.\n\n1. 端点 $l_f = 0, 1$ (実用上は $\\epsilon, 1-\\epsilon$) において, 一階条件の値を計算.\n1. 一階条件の値が異符号であれば, 二分法を用いて解を求める.\n1. 一階条件の値が同符号であれば, 端点解 (この場合, $l_f = 1$) 上の解を求める.\n\n::: {#find-zero-bracketing-corner .cell execution_count=1}\n``` {.julia .cell-code}\nfunction solve_bargaining(; w_m=1.0, w_f=0.5, γ_c=1.5, α_l=1.2, γ_l=1.5)\n\n    ϵ = 1e-9\n    left = w_m * (1 - (w_f / w_m)^(1 / γ_l) * ϵ) + w_f * (1 - ϵ) -\n           2 * (w_f / α_l)^(1 / γ_c) * ϵ^(γ_l / γ_c)\n    right = w_m * (1 - (w_f / w_m)^(1 / γ_l) * (1 - ϵ)) + w_f * ϵ -\n            2 * (w_f / α_l)^(1 / γ_c) * (1 - ϵ)^(γ_l / γ_c)\n\n    if left * right < 0\n        l_f = find_zero(\n            l_f -> w_m * (1 - (w_f / w_m)^(1 / γ_l) * l_f) + w_f * (1 - l_f) -\n                   2 * (w_f / α_l)^(1 / γ_c) * l_f^(γ_l / γ_c),\n            (ϵ, 1 - ϵ))\n        l_m = (w_f / w_m)^(1 / γ_l) * l_f\n    else\n        l_f = 1.0\n        x = find_zero(\n            x -> w_m * (1 - 1 / (1 + exp(x))) -\n                 2 * (w_m / α_l)^(1 / γ_c) * (1 / (1 + exp(x)))^(γ_l / γ_c),\n            0.0)\n        l_m = 1 / (1 + exp(x))\n    end\n\n    c = w_m * (1 - l_m) + w_f * (1 - l_f)\n    c_m = 0.5 * c\n    c_f = 0.5 * c\n    U = (c_m^(1 - γ_c) / (1 - γ_c)) + α_l * (l_m^(1 - γ_l) / (1 - γ_l)) +\n        (c_f^(1 - γ_c) / (1 - γ_c)) + α_l * (l_f^(1 - γ_l) / (1 - γ_l))\n    return (c_m=c_m, c_f=c_f, l_m=l_m, l_f=l_f, U=U)\nend\n```\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code code-fold=\"true\"}\nwf_grid = 0.1:0.01:0.9\nlm = [solve_bargaining(w_f=w).l_m for w in wf_grid]\nlf = [solve_bargaining(w_f=w).l_f for w in wf_grid]\np = plot(xlabel=L\"w_f\", legend=false, xlims=(0.1, 1.0))\nplot!(p, wf_grid, lm, lw=2, color=mypalette[6])\nplot!(p, wf_grid, lf, lw=2, color=mypalette[2])\n# direct labels at the right end (nudged apart since the lines converge there)\nannotate!(p, 0.915, lm[end] - 0.02, text(L\"l_m\", 9, :black, :left))\nannotate!(p, 0.915, lf[end] + 0.02, text(L\"l_f\", 9, :black, :left))\np\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![**Solution of bargaining problem.** $w_m = 1.0, \\alpha_l = 1.2, \\gamma_c = \\gamma_l = 1.5$.](nlopt_files/figure-typst/fig-sol-bargaining-output-1.svg){#fig-sol-bargaining}\n:::\n:::\n\n\n\n### 多変数の非線形方程式\n\n多変数の非線形方程式では Bracketing method は使えず, ニュートン法のような Non-bracketing method を用いる必要があります. そのため内点解と微分可能な関数を仮定しており, 端点解やスムースでない関数が想定される場合は使えません. そのような場合は, 原始的なグリッドサーチを用いるか, 後述するように非線形最適化問題として解く必要があります.\n\nなお, 多くの標準的な効用関数 (CRRA, CESなど) の場合, 一階条件は一変数の非線形方程式に帰着できます. 基本的には, 一変数の非線形方程式の方が収束が速く, 端点解の存在を確認しやすいので, 可能な場合は一変数の非線形方程式に帰着させることが望ましいです. 今回は学習のために, @eq-max-utility を3変数 ($c$, $l$, $\\lambda$) の非線形方程式 -@eq-foc-nonlinear-system として解いてみましょう. [NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/) を用いると便利です.\n\n$$\n\\begin{aligned}\nc^{-\\gamma_c} &= \\lambda \\\\\n\\alpha_l l^{-\\gamma_l} &= \\lambda w \\\\\nc &= w(1-l)\n\\end{aligned}\n$${#eq-foc-nonlinear-system}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction solve_nonlinear_system(; w=1.0, γ_c=1.5, α_l=1.2, γ_l=1.5)\n    f((c, l, λ), par) = [\n        λ * c^γ_c - 1,\n        α_l - λ * w * l^γ_l,\n        c - w * (1 - l)\n    ]\n    prob = NonlinearProblem(f, [0.5, 0.5, 0.35], 0.)\n    sol = solve(prob, NewtonRaphson())\n\n    return (c=sol.u[1], l=sol.u[2], λ=sol.u[3])\nend\n\nsolve_nonlinear_system()\n```\n\n::: {#solve-nonlinear-system .cell-output .cell-output-display execution_count=1}\n```\n(c = 0.469650429656516, l = 0.530349570343484, λ = 3.1069761107915044)\n```\n:::\n:::\n\n\n\n工夫として負の指数を避けるように式変形しています. これは最適化の際に, 負の数の負の数乗によってエラーが起きることを避けるためです.\n\n## 一変数の非線形最適化\n\nここからは, 非線形最適化の方法について解説します. 基本的には, 次の非線形関数 $f(\\cdot)$ の最小化問題を考えます.\n\n$$\n\\min_{\\mathbf{x} \\in \\mathcal{X}} f(\\mathbf{x}).\n$$\n\n制約条件として, $g(\\mathbf{x}) = \\mathbf{0}$ や $h(\\mathbf{x}) \\leq \\mathbf{0}$ を課すこともできますが, まずは制約なしの最適化問題を考えます. 制約付きの最適化問題については -@sec-constrained-opt 節 で解説します.\n\n一変数の非線形最適化は, -@sec-root-finding 節 で解説した, ニュートン法と二分法の analogy である, **準ニュートン法** (Quasi-Newton method) と **黄金分割法** (Golden-section search) で解くことができます. これらの方法は, それぞれニュートン法と二分法のように, 収束の速さと保証のトレードオフがあります. 準ニュートン法は, 収束が速い代わりに, 解が存在する保証がありません. 一方で, 黄金分割法は, 収束が遅い代わりに, 解が存在する区間を保証することができます.\n\n### 準ニュートン法\n\n求根法のニュートン法では, $f(x) = 0$ を解くために $x_{n+1} = x_n - f(x_n) / f'(x_n)$ という更新式を用いました. 最適化問題 $\\min_x f(x)$ では, 一階条件 $f'(x) = 0$ を解くことが目標ですので, ニュートン法を $f'(x) = 0$ に適用すると, 以下のアルゴリズムが得られます.\n\n::: {.callout-tip}\n\n## ニュートン法 (1変数)\n\n1. 初期値 $x_0$ を選ぶ. 停止条件として十分小さい $\\epsilon > 0$ を選ぶ.\n1. $x_{n+1} = x_n - \\frac{f'(x_n)}{f''(x_n)}$ を計算する.\n1. $|f'(x_{n+1})| < \\epsilon$ ならば停止し, $x_{n+1}$ を解として返す. そうでなければ, $n \\leftarrow n+1$ として2に戻る.\n\n:::\n\n二階微分 $f''(x_n)$ の計算が困難な場合, これを近似する方法が**準ニュートン法** (Quasi-Newton method) です. 代表的な方法として [BFGS法](https://ja.wikipedia.org/wiki/BFGS%E6%B3%95) があり, 一階微分の情報のみを用いて二階微分 (ヘッセ行列) を逐次的に近似します.\n\n-@sec-root-finding 節 で用いた CRRA 効用関数の最大化問題 (@eq-max-utility) を例にとりましょう. 制約を代入すると, 以下の一変数最大化問題になります.\n\n$$\n\\max_l v(l) = \\frac{(w(1-l))^{1-\\gamma_c}}{1-\\gamma_c} + \\alpha_l \\frac{l^{1-\\gamma_l}}{1-\\gamma_l}.\n$$\n\n::: {#fn-objective .cell execution_count=1}\n``` {.julia .cell-code}\nv(l; w=1.0, γ_c=1.5, α_l=1.2, γ_l=1.5) =\n    (w * (1 - l))^(1 - γ_c) / (1 - γ_c) + α_l * l^(1 - γ_l) / (1 - γ_l)\n```\n:::\n\n\n\n`Optim.jl` の `BFGS()` を用いて解くことができます. `BFGS()` は多変数関数に対応する手法であるため, 一変数であってもベクトルの形で表現する必要があります. また, `Optim.jl` は最小化を行うため, 目的関数の符号を反転させます. なお, $l \\in (0, 1)$ の制約を考慮するために `Fminbox` を用います.^[-@sec-non-bracketing 節 で説明したように, 定義域の変換で対処することも可能です.]\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nϵ = 1e-9\nresult = optimize(l -> -v(l[1]), [ϵ], [1.0 - ϵ], [0.5], Fminbox(BFGS()))\nresult.minimizer[1]\n```\n\n::: {#optim-bfgs .cell-output .cell-output-display execution_count=1}\n```\n0.530349570336863\n```\n:::\n:::\n\n\n\n求根法のニュートン法と同様に, 初期値の選び方によっては収束しない場合があり, 大域的な最適解への収束は保証されません.\n\n**数値微分**\n\nニュートン法系のアルゴリズムは, 一階微分や二階微分を必要とします. 解析的に導関数が分かっている場合は, それを勾配として `optimize()` に渡すことでより高速に解くことができます. 解析的に分からない場合は導関数を数値的に求めますが, その方法 (有限差分・複素ステップ・自動微分) は -@sec-differentiation 節 で扱います. `Optim.jl` は勾配を指定しなければ自動微分などで勾配を計算します.\n\n**デフォルトの設定**\n\n`Optim.optimize()` では, メソッドを指定せず区間も指定しない場合は, デフォルトでは [Nelder-Mead法](https://ja.wikipedia.org/wiki/%E3%83%8D%E3%83%AB%E3%83%80%E3%83%BC%E2%80%93%E3%83%9F%E3%83%BC%E3%83%89%E6%B3%95) が用いられます (`NelderMead()`). これは導関数を必要としない最適化アルゴリズムです. また, 勾配を指定した場合でも, BFGS法のメモリ使用量を改善した [L-BFGS法](https://ja.wikipedia.org/wiki/L-BFGS%E6%B3%95) (`LBFGS()`) が用いられます.\n\n\n### 黄金分割法 {#sec-golden-section}\n\n二分法が区間 $[a, b]$ において $f(a) \\cdot f(b) < 0$ (中間値の定理) を利用して区間を半分に分割していくのに対し, 黄金分割法は関数が区間内で**単峰** (unimodal) であること, すなわち極値が一つだけ存在することを仮定し, 黄金比を用いて区間を縮小していきます.\n\n::: {.callout-tip}\n\n## 黄金分割法\n\n最小化問題 $\\min_{x \\in [a, b]} f(x)$ を解く. 黄金比を $\\varphi = \\frac{\\sqrt{5}-1}{2} \\approx 0.618$ とする.\n\n1. 区間 $[a, b]$ を選ぶ. 停止条件として十分小さい $\\epsilon > 0$ を選ぶ.\n1. 内分点 $x_1 = a + (1-\\varphi)(b-a)$, $x_2 = a + \\varphi(b-a)$ を計算する.\n1. $f(x_1) \\leq f(x_2)$ ならば $b \\leftarrow x_2$ とし, そうでなければ $a \\leftarrow x_1$ とする.\n1. $|b - a| < \\epsilon$ ならば停止し, $\\frac{a+b}{2}$ を解として返す. そうでなければ, 2に戻る.\n\n:::\n\n![Visualization of Golden Section Search](/static/cetz/golden_section.svg){#fig-golden-section width=80%}\n\n@fig-golden-section は単峰関数 $f$ に対する黄金分割法の一ステップを表しています. 内分点 $x_1, x_2$ で関数値を比較し, $f(x_1) > f(x_2)$ であるため極小値は $x_1$ より右側にあると判断でき, 区間の左端を $a \\leftarrow x_1$ (赤い破線) に更新して探索区間を縮小します.\n\n各ステップで区間が $\\varphi \\approx 0.618$ 倍に縮小されるため, 単峰関数であれば収束が保証されます. なぜ内分比に黄金比を取るのかについては, -@sec-apdx-golden 節 で証明します. ただし, 準ニュートン法と比較すると収束速度は遅くなります (線形収束). `Optim.jl` の `GoldenSection()` を用いて解くことができます (`NonlinearSolve.jl` も同名の関数をエクスポートしているため, `Optim.GoldenSection()` と修飾して呼びます).\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nϵ = 1e-9\nresult = optimize(l -> -v(l), ϵ, 1 - ϵ, Optim.GoldenSection())\nresult.minimizer\n```\n\n::: {#optim-golden .cell-output .cell-output-display execution_count=1}\n```\n0.5303495600624788\n```\n:::\n:::\n\n\n\n二分法と同様に, 適切な区間を指定すれば収束が保証されるため, 準ニュートン法よりも堅牢な方法です.\n\n**デフォルトの設定**\n\n`Optim.optimize()` では, メソッドを指定せずに区間を指定した場合は, デフォルトでは黄金分割法を改良した [Brent法](https://ja.wikipedia.org/wiki/%E3%83%96%E3%83%AC%E3%83%B3%E3%83%88%E6%B3%95) が用いられます (`Brent()`).\n\n\n## 多変数の非線形最適化\n\n### 単純なケース\n\n一変数の場合と同様に, 多変数関数 $f: \\mathbb{R}^n \\to \\mathbb{R}$ の最小化も, 一階条件 $\\nabla f(\\mathbf{x}) = \\mathbf{0}$ を解く問題として捉えられます. これは -@sec-root-finding 節 の多変数求根法を最適化に応用したものです. ニュートン法は, ヤコビアンの代わりにヘッセ行列 $\\nabla^2 f$ を用いて更新します.\n\n::: {.callout-tip}\n\n## ニュートン法 (多変数)\n\n1. 初期値 $\\mathbf{x}_0$ を選ぶ. 停止条件として十分小さい $\\epsilon > 0$ を選ぶ.\n1. $\\mathbf{x}_{n+1} = \\mathbf{x}_n - \\left[\\nabla^2 f(\\mathbf{x}_n)\\right]^{-1} \\nabla f(\\mathbf{x}_n)$ を計算する.\n1. $\\|\\nabla f(\\mathbf{x}_{n+1})\\| < \\epsilon$ ならば停止する. そうでなければ $n \\leftarrow n+1$ として2に戻る.\n\n:::\n\n目的関数が滑らかで局所最適点が1つしかない場合は, 初期値の近傍を下っていく**局所的手法** (local method) だけで大域的最適点に到達できます. 一変数の場合と同様, ヘッセ行列とその逆行列の計算は高コストなため, 実際には**準ニュートン法** (BFGS) が広く使われます. BFGS はヘッセ行列 (今度は $n \\times n$ 行列) を一階微分の履歴から逐次的に近似します. 勾配すら利用できない場合は, 導関数を必要としない **Nelder-Mead 法** (単体法) が使えます.\n\n例として, 資本 $k$ と労働 $l$ を投入する企業の利潤最大化を考えます.\n\n$$\n\\max_{k, l} \\pi(k, l) = k^\\alpha l^\\nu - r k - w l, \\qquad \\alpha + \\nu < 1.\n$$\n\n一階条件は「限界生産物 = 要素価格」, すなわち $\\alpha k^{\\alpha-1} l^\\nu = r$ と $\\nu k^\\alpha l^{\\nu-1} = w$ です.\n\n::: {#fn-profit .cell execution_count=1}\n``` {.julia .cell-code}\nprofit(k, l; α=0.3, ν=0.5, r=0.1, w=1.0) = k^α * l^ν - r * k - w * l\n```\n:::\n\n\n\n$k, l > 0$ の正値制約を満たすため, 対数をとった変数 $(\\log k, \\log l)$ について最適化します.^[-@sec-non-bracketing 節 で述べた定義域の変換です. 指数関数を通すことで, 任意の実数が正の $k, l$ に対応します.] `Optim.jl` の `BFGS()` と, 導関数を使わない `NelderMead()` の両方で解いてみましょう.\n\n::: {#optim-multivariate .cell execution_count=1}\n``` {.julia .cell-code}\nobj(a) = -profit(exp(a[1]), exp(a[2]))\nres_bfgs = optimize(obj, [0.0, 0.0], BFGS())\nres_nm = optimize(obj, [0.0, 0.0], NelderMead())\nprintln(\"BFGS:        \", round.(exp.(Optim.minimizer(res_bfgs)), digits=4))\nprintln(\"Nelder-Mead: \", round.(exp.(Optim.minimizer(res_nm)), digits=4))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBFGS:        [2.7557, 0.4593]\nNelder-Mead: [2.7553, 0.4592]\n```\n:::\n:::\n\n\n\nどちらも同じ最適点 $(k, l) \\approx (2.76, 0.46)$ に収束します.\n\n### 複雑なケース\n\n単純なケースでは, どの初期値から出発しても同じ最適点に収束しました. これは目的関数が (対数変換の後に) 凸で, 局所最適点がただ1つだったからです. しかし, 構造推定の目的関数 (SMM や GMM の目的関数など) をはじめ, 多くの経済モデルの目的関数は多峰性 (multimodal, 非凸) をもつ可能性があり, 局所最適点が複数存在する場合があります. このとき最適化法は2種類に大別されます.\n\n- **局所的手法** (local method): 初期値の近くの谷を下っていく. BFGS や Nelder-Mead はこれにあたり, 収束は速いが, たどり着く最適点は初期値に依存する. 悪い初期値では, 大域的最適点でない局所最適点に捕まる.\n- **大域的手法** (global method): 定義域全体を系統的 (あるいは確率的) に探索し, 大域的最適点を探す. 探索範囲 (box 制約) を指定する必要があり, 一般に局所的手法より多くの関数評価を要する.\n\n大域的手法を数多く備えた代表的なライブラリが [NLopt](https://nlopt.readthedocs.io/) です. Julia では [Optimization.jl](https://docs.sciml.ai/Optimization/stable/) が, NLopt を含む多くのソルバーを共通のインターフェースで扱えます. 問題を `OptimizationProblem` として組み立て, ソルバー (例えば NLopt の `NLopt.GN_DIRECT_L()`) を指定して `solve` するだけです. 以下ではこの Optimization.jl 経由で NLopt を呼びます.^[NLopt も `optimize` を輸出し `Optim.jl` と衝突するため, `OptimizationNLopt` と `NLopt` は `using` ではなく `import` で読み込んでいます.]\n\n多峰性の例として, 多数の局所最適点をもつ Rastrigin 関数を最小化します.\n\n$$\nf(\\mathbf{x}) = 10 n + \\sum_{i=1}^{n} \\left[ x_i^2 - 10 \\cos\\left(2\\pi x_i\\right) \\right], \\qquad \\mathbf{x} \\in [-5.12, 5.12]^n.\n$$\n\n放物線 $\\sum_i x_i^2$ に余弦波の細かい起伏を重ねた関数で, 定義域の至る所に局所最適点をもちます. 大域的最適点は原点 $\\mathbf{x} = \\mathbf{0}$ で, そこで $f = 0$ です. 以下では $n = 2$ とします.\n\n::: {#fn-rastrigin .cell execution_count=1}\n``` {.julia .cell-code}\nrastrigin(x) = 10 * length(x) + sum(x .^ 2 .- 10 .* cos.(2π .* x))\n```\n:::\n\n\n\n@fig-rastrigin にこの関数の形状を示します. 放物線状のなだらかな椀の上に細かい起伏が重なり, 至る所に局所最適点 (谷) があるのが分かります.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code code-fold=\"true\"}\nxs = range(-5.12, 5.12, length=150)\nZ = [rastrigin([x, y]) for y in xs, x in xs]\nsurface(xs, xs, Z, c=:inferno, xlabel=L\"x_1\", ylabel=L\"x_2\",\n    zlabel=L\"f(\\mathbf{x})\", colorbar=false, camera=(35, 40), size=(560, 440))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![**Rastrigin function ($n = 2$).** Local minima appear throughout the domain.](nlopt_files/figure-typst/fig-rastrigin-output-1.svg){#fig-rastrigin}\n:::\n:::\n\n\n\nまず, 単純なケースでも使った局所的手法 (Nelder-Mead) を, 原点から離れた初期値 $[3, 3]$ から走らせます.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nres_local = optimize(rastrigin, [3.0, 3.0], NelderMead())\n(x=round.(Optim.minimizer(res_local), digits=3),\n    f=round(Optim.minimum(res_local), digits=3))\n```\n\n::: {#optim-local-trap .cell-output .cell-output-display execution_count=1}\n```\n(x = [2.985, 2.985], f = 17.909)\n```\n:::\n:::\n\n\n\n局所最適点 $(2.98, 2.98)$ に捕まり, $f \\approx 17.9$ と大域的最適値 $0$ から大きく外れています. 初期値を原点の近くにとれば $f = 0$ に収束しますが, どの谷に落ちるかは初期値次第です.\n\n次に, NLopt の大域的手法 DIRECT-L で探索範囲 $[-5.12, 5.12]^2$ 全体を探索します. Optimization.jl では目的関数を `f(u, p)` の形 (`u` が変数, `p` がパラメータ) で与え, 探索範囲を `lb` / `ub` で指定します.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\noptf = OptimizationFunction((u, p) -> rastrigin(u))\nprob = OptimizationProblem(optf, [3.0, 3.0]; lb=[-5.12, -5.12], ub=[5.12, 5.12])\nsol = solve(prob, NLopt.GN_DIRECT_L(), maxiters=5000)\n(x=round.(sol.u, digits=3), f=round(sol.objective, digits=3))\n```\n\n::: {#optim-global .cell-output .cell-output-display execution_count=1}\n```\n(x = [0.0, 0.0], f = 0.0)\n```\n:::\n:::\n\n\n\n初期値によらず大域的最適点 $\\mathbf{x} = \\mathbf{0}$ ($f = 0$) にたどり着きます. DIRECT (DIviding RECTangles) は探索範囲を系統的に分割していく決定論的な手法で, 初期値の値には依存しません.\n\n実務では, 大域的手法で有望な領域を絞り込んでから局所的手法で精密化する, という組み合わせがよく使われます. NLopt の **MLSL** (Multi-Level Single-Linkage, `:G_MLSL_LDS`) は, 定義域全体から多数の初期値をサンプルして局所的手法を繰り返し適用する **multistart** 法で, この考えを体系化したものです.\n\n## 制約付き非線形最適化 {#sec-constrained-opt}\n\n経済モデルでは, 予算制約などの制約付き最適化が中心的です. 一般に, 等式制約 $g(\\mathbf{x}) = \\mathbf{0}$ と不等式制約 $h(\\mathbf{x}) \\leq \\mathbf{0}$ のもとで $f(\\mathbf{x})$ を最小化する問題を考えます. ラグランジュ関数\n\n$$\n\\mathcal{L}(\\mathbf{x}, \\lambda, \\mu) = f(\\mathbf{x}) - \\lambda^\\top g(\\mathbf{x}) - \\mu^\\top h(\\mathbf{x})\n$$\n\nの停留点を KKT 条件のもとで求める, というのが基本的な考え方です. 数値的には主に3つのアプローチがあります.\n\n**変数消去.** 等式制約を代入して未知数を減らし, 制約なし問題に帰着させる方法です. 一変数の例で予算制約 $c = w(1-l)$ を代入したのがこれにあたります. 2財の消費者問題を例にとりましょう.\n\n$$\n\\max_{c_1, c_2} c_1^a c_2^b \\quad \\text{s.t.} \\quad p_1 c_1 + p_2 c_2 = m.\n$$\n\n予算制約から $c_2 = (m - p_1 c_1)/p_2$ を代入すれば, $c_1$ のみの一変数問題になります.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\np1, p2, m = 1.0, 2.0, 10.0\nu2(c1; a=0.4, b=0.6) = c1^a * ((m - p1 * c1) / p2)^b\nres = optimize(c1 -> -u2(c1), 1e-6, m / p1 - 1e-6, Optim.GoldenSection())\nc1 = Optim.minimizer(res)\n(c1=c1, c2=(m - p1 * c1) / p2)\n```\n\n::: {#constrained-substitution .cell-output .cell-output-display execution_count=1}\n```\n(c1 = 3.9999999973978277, c2 = 3.0000000013010863)\n```\n:::\n:::\n\n\n\nコブ・ダグラス型の需要 $c_1 = a m / p_1 = 4$, $c_2 = b m / p_2 = 3$ と一致します.\n\n**箱制約.** $0 \\leq c \\leq \\bar{c}$ のような単純な上下限 (box constraint) は, ソルバーに下限 `lb` と上限 `ub` を渡すだけで直接扱えます. 変数消去した消費者問題を, 導関数を使わない NLopt の BOBYQA 法で解いてみましょう.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nnegu(c1, p) = -(c1[1]^0.4 * ((m - p1 * c1[1]) / p2)^0.6)\nprob = OptimizationProblem(OptimizationFunction(negu), [2.0];\n    lb=[1e-6], ub=[m / p1 - 1e-6])\nsol = solve(prob, NLopt.LN_BOBYQA(), maxiters=10_000)\n(c1=sol.u[1], c2=(m - p1 * sol.u[1]) / p2)\n```\n\n::: {#constrained-box .cell-output .cell-output-display execution_count=1}\n```\n(c1 = 4.0000000167979515, c2 = 2.9999999916010243)\n```\n:::\n:::\n\n\n\n変数消去と同じ解 $(c_1, c_2) = (4, 3)$ が得られます.\n\n**一般の制約.** 変数消去が難しい一般の等式・不等式制約は, 制約関数を直接ソルバーに渡して扱います. 制約 $g(\\mathbf{x})$ を `cons` で, その下限・上限を `lcons` / `ucons` で与えます (等式制約は下限 = 上限). 予算制約 $p_1 c_1 + p_2 c_2 = m$ を消去せずに, 制約を扱える NLopt の COBYLA 法で解いてみましょう.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nnegu2(c, p) = -(c[1]^0.4 * c[2]^0.6)\nbudget(res, c, p) = (res[1] = p1 * c[1] + p2 * c[2] - m)\noptf = OptimizationFunction(negu2; cons=budget)\nprob = OptimizationProblem(optf, [2.0, 4.0]; lcons=[0.0], ucons=[0.0],\n    lb=[0.0, 0.0], ub=[50.0, 50.0])\nsol = solve(prob, NLopt.LN_COBYLA(), maxiters=10_000)\nsol.u\n```\n\n::: {#constrained-cobyla .cell-output .cell-output-display execution_count=1}\n```\n2-element Vector{Float64}:\n 4.0000000528577555\n 2.9999999735711227\n```\n:::\n:::\n\n\n\n予算制約 $p_1 c_1 + p_2 c_2 - m$ の下限・上限をともに $0$ とすることで等式を表しています. 同じ解 $(c_1, c_2) = (4, 3)$ が得られます. NLopt には勾配を使う SLSQP など制約付き問題向けの手法も揃っており, 真の内点法が必要であれば次節の Ipopt を使います.\n\nより複雑な制約付き問題では, 次に述べるように, 問題を宣言的に記述してソルバーに渡す方法が便利です.\n\n## Mathematical Programming\n\nより強力な方法として, 解きたい最適化問題を直接ソルバーにかける方法があります. Juliaの場合は [JuMP.jl](https://jump.dev/JuMP.jl/stable/) が有名です. ここでは, @eq-couple-problem を JuMP を用いて解いてみましょう.\n\n::: {#solve-jump .cell execution_count=1}\n``` {.julia .cell-code}\nfunction solve_jump(; w_m=1.0, w_f=0.5, γ_c=1.5, α_l=1.2, γ_l=1.5)\n\n    model = Model(Ipopt.Optimizer)\n    set_silent(model)\n    set_attribute(model, \"print_level\", 0)\n    set_attribute(model, \"sb\", \"yes\")   # suppress the Ipopt banner\n    @variables(model, begin\n        0 <= c_m\n        0 <= c_f\n        0 <= l_m <= 1\n        0 <= l_f <= 1\n    end)\n\n    @objective(\n        model,\n        Max,\n        (c_m^(1 - γ_c) / (1 - γ_c)) + α_l * (l_m^(1 - γ_l) / (1 - γ_l)) +\n        (c_f^(1 - γ_c) / (1 - γ_c)) + α_l * (l_f^(1 - γ_l) / (1 - γ_l))\n    )\n\n    @constraint(model, c_m + c_f == w_m * (1 - l_m) + w_f * (1 - l_f))\n\n    optimize!(model)\n\n    return (\n        c_m=value(c_m),\n        c_f=value(c_f),\n        l_m=value(l_m),\n        l_f=value(l_f),\n        U=objective_value(model)\n    )\nend\n```\n:::\n\n\n\n@fig-sol-bargaining と同じ結果が得られました.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code code-fold=\"true\"}\nwf_grid = 0.1:0.01:0.9\nlm = [solve_jump(w_f=w).l_m for w in wf_grid]\nlf = [solve_jump(w_f=w).l_f for w in wf_grid]\np = plot(xlabel=L\"w_f\", legend=false, xlims=(0.1, 1.0))\nplot!(p, wf_grid, lm, lw=2, color=mypalette[6])\nplot!(p, wf_grid, lf, lw=2, color=mypalette[2])\nannotate!(p, 0.915, lm[end] - 0.02, text(L\"l_m\", 9, :black, :left))\nannotate!(p, 0.915, lf[end] + 0.02, text(L\"l_f\", 9, :black, :left))\np\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![**Solution of bargaining problem by JuMP.** $w_m = 1.0, \\alpha_l = 1.2, \\gamma_c = \\gamma_l = 1.5$.](nlopt_files/figure-typst/fig-sol-jump-output-1.svg){#fig-sol-jump}\n:::\n:::\n\n\n\nとても便利に思えますが, いくつか注意点があります.\n\n1. 計算の正しさが保証されない. アルゴリズムの中身がブラックボックスであり, 研究者自身が解の正しさを保証できない. 端点解を見逃す可能性や収束しない可能性がある.\n1. 計算が遅い. 一階条件を直接解く場合と比べると, 問題の複雑さが増すため, 計算が遅くなる. より大規模なモデルを解きたい場合には, 致命的な問題となる可能性がある.\n\n検算目的で使うぐらいに留めておくのが良いでしょう.\n\n",
    "supporting": [
      "nlopt_files"
    ],
    "filters": []
  }
}