---
title: 結婚の経済学
---

## 結婚の経済学的な意義

結婚は主体的な選択である以上, 経済学の分析ではインセンティブの構造を理解することが必要です. 様々な要因が結婚の意思決定に影響を与えますが, 主に議論されるのは次の4つです.

1. **規模の経済**: 実質的な所得効果
1. **公共財の供給**: 家事労働, 子どもなど
1. **リスクシェアリング**: 所得リスクなど
1. **愛**: 上記3つで説明されない (確率的) 要素

### 規模の経済

二人以上で住む場合は, 家賃や光熱費などの固定費を分担できたり, 食事をまとめて作ることでコストが下げられるなど, 消費の効率が上がることがあります. これを経済学では規模の経済 (economies of scale) と呼びます. 正確にモデル化すると複雑化してしまうので, ほとんどの研究では OECD の統計による簡便な尺度を用います.


::: {.callout-note}

## OECD Equivalence Scale

OECD equivalence scale は, 二人目以降の世帯員が消費する財の量を 0.7, 子どもは 0.5 として, 世帯の消費を調整する尺度である. 典型的な夫婦と子ども $n$ 人の世帯の消費は $C(n) = 1 + 0.7 + 0.5n$ と表される. 世帯所得を $Y$ とすると, 世帯の消費水準は $Y/C(n)$ で表される.

なお, 近年は再計算が行われて, 大人は 0.5, 子どもは 0.3 に調整されており, これを OECD-modified equivalence scale と呼ぶ.

:::

他の簡便な尺度として, 世帯員の人数の根号をとる $C(n) = \sqrt{n}$ とする方法もあります.

### 公共財の供給

結婚している場合, 独身の場合と比べて, 家事労働の分担や子どもの養育などの便益を得ることができます. これらは, 夫婦間で共有され, かつ消費の際に競合しないため, 公共財 (public goods) と呼ばれます.

公共財をモデル化する場合は, 様々な流儀があり, 子どもの人数 $n$ に応じて効用を $u(n)$ とする方法や, 家事労働の分担を考慮して効用を $u(h_1, h_2)$ とする方法などがあります.


### リスクシェアリング

夫婦が共に働いている場合, 片方の所得が減少しても, もう片方の所得で生活を維持することができます. このように結婚は所得リスクを分散する効果があり, 経済学ではリスクシェアリング (risk sharing) と呼ばれます. ただし, リスクシェアリングは数ある経済学的な結婚の意義の中でも, それほど大きな効果はないと考えられています.

### 愛

結婚に最も重要な要素は愛であると考える人は多いでしょう. それらは否定されることではありませんが, 観察されることでもありません. そのため, 経済学のモデルでは, 愛は確率的な要素として扱われることが多いです. 夢のない話のように思えるかもしれませんが, 上記のような経済学的な要因を差し引いても, 結婚が成立するのは, 愛があるからだと考えることもできます.


::: {.callout-warning}

## 結婚の定義

近年では多様な形のパートナーシップも広がっているが, 本講義では, 注釈のない限り異性間の法律婚を対象とします. しかし, 特に西欧諸国では事実婚と法律婚の違いが小さくなっているため, 事実婚や同居 (cohabitation) を含めた研究も多いです.

:::

## 結婚モデルの2つの流派

結婚をモデル化するときには, 次の二つの流派があります.

**1. サーチモデル (Search and Matching Model)**

- @shimer2000 を起源とした毎期ランダムに相手を探す動学的モデル
- 結婚のタイミング (晩婚化) や再婚などを扱いやすい
- 講義では @greenwood2009, @greenwood2016 を紹介

**2. 摩擦のない結婚市場モデル (Frictionless Marriage Market)**

- @choo2006 に始まる, 初期時点で全ての人が結婚相手を見つけるモデル
- より詳細な家庭の意思決定 (家庭内配分など) をモデル化しやすい
- 講義では一般枠組みとして @galichon2019 を扱い, その特殊ケースとして @choo2006 を導く
- 応用として @ciscato2025, @reynoso2024 を紹介

この講義では順番にそれぞれのモデルを紹介していきます.